### ISSUE TITLE
target statistics

### ISSUE THREAD

**Issue by thednainus** [EpiModel/EpiModel#601]
I am not sure whether here is the right place to ask this question:
I am trying to estimate the target statistics for my model.
I only have the information from a paper which says:

Data were collected in 3 different time points:
Number of total respondents = 299
Number of sexual partners = 699 (I'm assuming this are the alters)
Median number of male sexual partners = 6  [IQR = 2 - 11] (I'm assuming this are the ties)

Median partnership duration = 0.79 months [IQR = 0.03, 6.97]

Is it correct to say that my `mean degree = (2 * 6)/(299+699)`

So edges will then be `mean degree * n/2`
Where `n` is the number of individuals at the beginning of my simulation?

**Comment by sgoodreau** [comment]
Hello - 

There are a few pieces here that are hard to follow or don't seem to be consistent.  I think it is a function of the wording you are using in your summary, relative to what the full questions actually asked are, and what it is your model is intended to capture.

Remember that mean degree as typically defined in target stats for a tergm measures the mean number of partner a person in the network has in the cross-section, ie at a moment in time.

You mention 299 respondents, who say they collectively they had 699 partners.  Are those the partners they had over the course of some time period?  Or the partners they have ongoing on the day of study?

If the latter, it would suggest that mean degree is 699/299 = 2.34. If the former, then you don't have enough info to calculate mean degree from just those two numbers.

Then you say that median number of male partners is 6.  But if the 299 people had 699 partners total, their male partners are presumably a subset of that.  How could they then have a median of 5?  Something in there does not add up.  I am guessing the questions are asking about different things that you haven't told us about.

In either case, your mean degree calculation is not right : it should have partners in the numerator somewhere, and the people having those partners in the denominator somewhere.  6 is already normalized by number of partners, and 699 is also about number of partners but is in the denominator instead of the numerator. 

Translating meandegree into edges is indeed edges = mean degree * n/2, where n is the population size used during model estimation (and also typically during the start of your subsequent network simulation).

**Comment by thednainus** [comment]
Hi Steven,

Thanks for the explanation. And yes, you correctly understood my question.
The paper describes a study which analysed data from 3 different _"waves"_ collected at different times. 
From these 3 dataset they had a total of 299 people that answer their questionnaire. These 299 individuals reported collectively 699 partners. 
I am guessing that the difference between the two values for the _"mean degree"_ is because the number you calculated (699/299 = 2.34) is the **mean**, while the number they reported in the paper of 6 [IQR = 2.0 - 11] is the **median** number of sexual partners?

I think I got confused on the calculation of the mean degree, after reading this tutorial http://statnet.org/Workshops/ergm.ego/ergm.ego_tutorial.html#Practical_issues
in which `mean degree = (2 x nodes)/n`

Cheers,
Fabricia.

**Comment by sgoodreau** [comment]
For a right-tailed distribution (which typically includes sexual partners) the mean is larger than the median.  I don't really see a way for the reverse to be true for data like these.

One needs to be very careful about the details here.  For instance, was it set up where someone could answer a question about how many partners they had had total, and then they were also asked detailed partner-by-partner questions about a subset?  If so, the median of 6 may refer to the former, and the mean of 2.34 may refer to the latter.

In the end, our various tutorials and other materials can serve as a guide for helping people to learn how our methods and software works in reasonable detail, but every data situation is different, and users have to take their knowledge about the details of that data and adapt it as needed using first principles.  

On the workshop you link, to I see a place where it says `mean degree = (2 x ties)/n` but not one where it has nodes in the numerator.  Can you point me to where you see that?  If it says that we need to fix it.

**Comment by thednainus** [comment]
Sorry, it was a typo on my side, I meant _"ties"_ on the numerator and I've edited the post to fix it.

Back to mean and median, and based on you answer, I **don't think** from the paper I would have enough information to calculate the mean degree because the number of partners were reported for the _past 3 months_.

Is there any tutorial that have some explanation to calculate the mean degree when respondents were asked to report the partners in the past XX months?
I don't have access to the respondents answers to the questionnaire. 
(Sorry, this is not really my area, and I am just looking for a way of calculating the mean degree based on the data described on this paper (if possible. it might be that the paper does not provide enough information). The idea is to use EpiModel to get a transmission matrix that I will convert to a phylogenetic tree).

Thanks,
Fabricia.
