### ISSUE TITLE
Break plot.netsim and plot.netdx into subfunctions

### ISSUE THREAD

**Issue by smjenness** [EpiModel/EpiModel#662]
... to reduce complexity of entire function and reduce redundancy in code and  potential for error.

**Comment by AdrienLeGuillou** [comment]
could be related to #666

**Comment by smjenness** [comment]
Updated title to make sure we work on both netdx and netsim, given @sgoodreau's comment.

**Comment by chad-klumb** [comment]
Refactoring of formation, dissolution, and duration plotting for `netsim` and `netdx` was done in #702, saving ~1000 lines of code.

There is a nontrivial amount of redundancy remaining in other plotting functionalities (in plot.R).  It may be possible to save another (very roughly) ~500 lines of code by settling on a unified approach to plotting things that could also be applied to these "other" cases (dcm, icm, and epi plots).  Another option might be to combine dcm/icm/epi but leave them as distinct from formation/dissolution/duration.

I would consider this additional work a longer-term issue, and I'm not planning to work on it, but wanted to note what more could be done.  Note that some ylim issues (such as those of #676) might still exist for these "other" cases since they do not currently use the same plotting approach as formation/dissolution/duration.

**Comment by smjenness** [comment]
Thanks! I am content with closing this issue now, given all the work in #702. The other redundancies across other model classes are outside the scope of our current work.
