### ISSUE TITLE
Allow core EpiModel to handle multiple networks

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#669]
#667 

This was discussed several times in the past but I can't find the original issue.

The EpiModelCOVID already have a pretty simple way of dealing with this.

One of the major issue will be to handle a step between each network resimulation, as we do with EpiModelHIV where some information are pulled from the `main` network and used in the `casl` and `oof` networks.
This can be solved with a function (or a list of them) that could be passed in `param` or `control` and would be executed in between each network simulation. (such function would be of the form `function(dat) {...; return(dat)}`)

**Comment by chad-klumb** [comment]
I was asked to open a discussion on this topic, but we already have issues #667 and #669, so I'm starting by posting here.  It looks like Adrien has already been assigned to these.

@smjenness do you have more specific information as to what exactly you want to support in core EpiModel regarding multiple networks, and/or who you want to do it?

**Comment by chad-klumb** [comment]
In particular:

- are we allowing node sets to differ between networks, and
- are we allowing any number of dynamic (tergm model) networks and any number of static (ergm model) networks?

**Comment by smjenness** [comment]
Hi Chad - I can outline the primary issues/requests here by early next week.

**Comment by smjenness** [comment]
Some summary notes following our Zoom discussion today.

1. We would like to implement a somewhat general version of multi-layer networks into core EpiModel, following the approach of EpiModelHIV as a general template. For our purposes, multi-layer networks means the same node set but different edge sets in each layer. 
2. The starting point for this would be to wrap network initialization and simulation in a loop, defined by the length of the passed in `x` object to netsim, which can be a list of separate TERGMs. Other updates with this would be to handle the multi-layer structure in the node set changes: births (arrivals) and deaths (departures). We would also move the edges correction function from the network resimulation and into these demographic functions. 
3. Implement a pre-network resimulation function that would run directly before each resimulated network. This might be a list of functions, with the same length as the length of the `x` object. This would allow a flexible way to handle what we do in EpiModelHIV: recalculate the cross-network degree values needed for updated attributes in each network simulation.
4. With step 3 working, we could consider a general multi-layer version of the infection module, following something like our [COVID model approach](https://github.com/EpiModel/EpiModelCOVID/blob/main/R/mod-infection.R#L256-L359), but one complication here is that in core EpiModel vector indexing of the infection probability parameter is already defined as time since infection. So a more general approach would be needed to potentially index by multiple factors.
5. A more general approach to evolution of partnership types (evolution across networks) as a function of time to change of type. I will open a separate issue on that, but noting it here as related.

**Comment by smjenness** [comment]
Related, as noted, in https://github.com/EpiModel/EpiModelHIV-p/issues/141, we may want to revisit specifying the `nwstats.formula` argument for multi-layer networks.

**Comment by chad-klumb** [comment]
will be working on this in the form of various other issues/PRs for the time being

**Comment by krivit** [comment]
A bit late to this party, but I wonder if `ergm.multi`'s multilayer implementation might be of some use. It represents a multilayer network as a single block-diagonal one with some metadata and is treated like one by all the terms that aren't aware of layers, which means that it can be fed directly to all the `tergm` functions, including EDApprox and EGMME.
