### ISSUE TITLE
consolidate control arguments to `netest`?

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#673]
`netest` currently has three control arguments: `set.control.ergm`, `set.control.stergm` (deprecated), and `set.control.tergm`.  Upon adding support for `ergm.ego`, it would also need `set.control.ergm.ego`.

These could be consolidated into a single argument (possibly just called `control`) since only one of `ergm`, `ergm.ego`, `stergm`, and `tergm` is called on a given call to `netest`.  The class of the `control` argument is checked (by `ergm`, `tergm`, etc.) to prevent incorrect controls being passed.

We wouldn't be able to consolidate controls to e.g, `netdx` and `netsim` similarly because in general we may perform both `ergm` and `tergm` simulation in a single call to `netdx` or `netsim`.  So, in that sense, consolidating controls to `netest` would introduce something of an inconsistency in `EpiModel` control argument handling.

@smjenness would you prefer to stick with the current `set.control.*` arguments to `netest` or combine them into just `control`?

**Comment by smjenness** [comment]
I can see the pros and cons of this, but I feel like the inconsistency of the control function naming between netest and netdx/netsim may be confusing. So I would opt to leave it as is, even if that means adding yet another control arg type with ergm.ego. 

@martinamorris what do you think?

**Comment by martinamorris** [comment]
@smjenness IIUC, the `set.control.X` arguments are already "inconsistent" between `netdx` and `netsim`, since the latter only includes `X` = `ergm` or `tergm`, while the former will also include `X` = `ergm.ego`.  

* I'm not sure what the long term status of `set.control.stergm` is, given that we are hoping to deprecate `stergm`.   @chad-klumb can you pls. clarify?

So perhaps there are a couple of other possibilities to consider:

* See if there is a way to implicitly identify the type of simulation called for in `netsim` (`ergm` or `tergm`) so that the control call can be simplified to `control`.

* If not, we can still make the prefix consistent

    * `set.control` for `netest`, and `set.control.X` for `netsim`

    *  `control` for `netest`, and `control.X` for `netsim`

**Comment by chad-klumb** [comment]
`set.control.stergm` is deprecated and will be removed in a future version

a single `netsim` call, even with a single network (as in core `EpiModel`) can still perform both `ergm` simulation (for generating an "independent" initial network) and `tergm` simulation (for subsequent EDA simulation on each time step)

the PR #678 implements support for `ergm.ego` in `netest`, adding `set.control.ergm.ego`, so if that's the way we want to go, this issue can be closed
