### ISSUE TITLE
should we print duration table from netsim object when it is available?

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#737]
In `print.netdx` we print both the duration and dissolution tables when they are available:

https://github.com/EpiModel/EpiModel/blob/22adcf11e8633c29a3d6754fa19d08e22c12ec7d/R/print.r#L147-L156

In `print.netsim` we only ever print dissolution:

https://github.com/EpiModel/EpiModel/blob/22adcf11e8633c29a3d6754fa19d08e22c12ec7d/R/print.r#L249-L276

Should this be changed to also print duration in `print.netsim` when it is available?

**Comment by smjenness** [comment]
Yes, I think it would make sense to include both the duration and dissolution tables in `print.netsim`, consistent with `print.netdx`. @sgoodreau : do you foresee any issue here (e.g., weird censoring issues that could complicate interpretation of duration diagnostics in an open population sim... )

**Comment by sgoodreau** [comment]
There are a host of feature-not-bug reasons why durations from `net.sim` would not match the original target values, once one adds in full simulation dynamics.  For instance, see https://github.com/EpiModel/EpiModelHIV-p/issues/23#issuecomment-1183567633. This is somewhat analogous to examples like the seroadaptive example in NME where overall mean degree changes with epidemic expansion.  So as a minimum, we should make very clear somehow that these metrics should be thought of as model output more than as model diagnostics per se.  As long as we do that, I think we're good. 

I think dissolution is more buffered from these kind of effects than duration is, but if there is reasonably complex heterogeneity in the diss model they might start to be as well.

Beyond that, I don't see major issues.

**Comment by martinamorris** [comment]
Agree with all that @sgoodreau said.  It seems like the value of including the duration table is 

1. To see how long duration takes to burn in, in case the mean duration dist'n is something that you're relying on for further analysis. 
 
2. To make sure it does eventually hit the target.  If it doesn't that might be useful information for understanding something that you didn't expect.

Is there any value to saving the mean age of active ties?

**Comment by sgoodreau** [comment]
And as long as we only allow time-non-varying dyadic independent dissolution models in EpiModel, MAOET should always be able to tell you in the shorter run where durations are heading in the longer run.

**Comment by martinamorris** [comment]
> What we call duration here _is_ the mean age of active ties. It used to be different things in different places (including when plotting vs printing the very same object) but one of the tasks this year was making it consistent throughout. There are a bunch of costs/benefits here and we went with this after some discussion because the benefits are greater than they at first seem.

Maybe this makes the point.  I think it's confusing to use the term "duration" for active tie age.  We've been pretty sloppy in our terminology (probably b/c we've been so focused on the simple exponential mean).  But as you get into modeling tie length, these terminological distinctions become important.  This is a bit like calling the nodal age variable life expectancy.  Admittedly, "duration" can mean time since formation, or completed tie length.  It's not a precise term.  But I think the most common popular usage is completed tie length.  

Yes, I know it would mean lots of changes.  I just think it's not helpful to perpetuate a mistake we made early on.

**Comment by sgoodreau** [comment]
I have lots of thoughts on this issue, and not the time at the moment to lay them all out [ed: OK by the time I finsihed the comment I'd laid out more than I epxected to, but without going into details of justification].  I agree with Sam that this is a much bigger question than this issue and should be moved to a new issue or discussion, and not hold up the release of these improvements to EpiModel. Resolving this is a complex matter, and ultimately ties into many of the issues that we keep butting up against and honestly need an R01 to fully lay out.

My short answer is that I fully agree that we should be more consistent in terminology. That said, I strongly favor doubling-down on mean age of extant ties (MAOET) as the main metric we focus on, with duration info being available to people but not emphasized as the thing one is trying to match. That is, no longer thinking of MAOET as merely an estimator of duration, but as the target statstic of interest itself.  The choice of duration over MAOET as the single statistic used to parameterize a distribution is arbitrary, and we only focus on it because it's more familiar to people.  But it is much more challenging to measure in the real world and presents more challenging bias issues in simulated data as well. It's not unlike the early decision to using a persistence model (since it's the more natural model), but calling it a dissolution model for many years because the concept is more familiar, but then eventually deciding it was better to call it persistence after all, and just be clear to people.

And if and when we ever move away from time-homogenous dissolution models, I think we still shouldn't actually focus on duration as the target statstic, but rather time-specific dissolution probabilities.  Duration is always an interesting output, but not necessarily an input.

All of this will need lots more documentation/discussion of both, and caveats about the known biases in measuring duration in dynamic sims in the documentation, with extremely long durations needed to minimize this. This means going back and changing the wording not just in the EpiModel code, but also in NME, Sunbelt workshops, etc.

**Comment by chad-klumb** [comment]
> @chad-klumb : we are good to go in terms adding the duration table here, thanks!

I'll make a PR for this soon.

**Comment by martinamorris** [comment]
Will move the terminology question to a new issue.  @sgoodreau I agree that the mean age of active ties is the key metric for `netdx` purposes.  But as Emily's dissertation issues revealed, the duration of completed ties is also important to understand.
