### ISSUE TITLE
prevent crashes on `saveout.net` if some elements do no exist

### ISSUE THREAD

**Issue by AdrienLeGuillou** [EpiModel/EpiModel#790]
related to #789

**Comment by AdrienLeGuillou** [comment]
fixed by #791

**Comment by chad-klumb** [comment]
Just a thought, but since `NULL` could be a valid value we actually want to save, should we consider replacing things like `out[[el.name]][[s]] <- dat[[el.name]]` with `out[[el.name]] <- c(out[[el.name]], list(dat[[el.name]]))`?  The latter appends `dat[[el.name]]` to `out[[el.name]]` even if `dat[[el.name]]` is `NULL`.

**Comment by AdrienLeGuillou** [comment]
I see your point, I opened a new issue so I won't forget about it
