### ISSUE TITLE
Check why node stays too long in I(infectious) component

### ISSUE THREAD

**Issue by Pie923** [EpiModel/EpiModel#809]
Dear all, 

Thank you so much for your previous help in answering my questions. I have used your example codes for my research aim but unfortunately found my codes didn't achieve what I'd want. Specifically, I try to build a SEIAR model for COVID-19 transmission where I and A refer to 2 passways one can go through. In my simulation results, infected individuals stay too long in I component when they should have gone to R component. I suspect there are bugs in my module codes but I couldn't find them. Could you please help me check and find this?  My example simulation result is here: https://github.com/Pie923/Epimodel/blob/main/check_module_error.nb.html  and the code to reproduce this is here: https://github.com/Pie923/Epimodel/blob/main/check_module_error.R

Thank you so much if you can help!

Best, 

Li

**Comment by smjenness** [comment]
I have reviewed your model. Everything looks in order to me. The transition from I to R is occurring as expected. Note that you have very few to no infections occurring in many simulations because you are only seeding the epidemic in one person, and that one person (node 21) has a low network degree (limited social contacts relevant for disease transmission). For example, you can see the degree over time like this: 

```r
sapply(1:200, function(x) get_degree(network.collapse(nw, at = x))[21])
```

You can see here that the degree is 0 across the critical time period where infection could possibly happen before node 21 recovers. The solution here is to see the infection differently (e.g., have more than one seed node, or a seed node who is active at time step 1. You could check who is active at time 1, for example, with:

```r
get.dyads.active(nw, at = 1)
```

Note also, that you are running your model out for 1500 time steps, but using a built-in dynamic network that only has observations for 100 time steps. This means that after time step 100, there will be no change in edges. The caveats for this are described [here](https://github.com/EpiModel/EpiModel-Gallery/blob/main/2018-08-ObservedNetworkData/model.R#L92-L116).

Hope that helps!

Note that
