### ISSUE TITLE
Quantiles not plotted correctly

### ISSUE THREAD

**Issue by BaylorFain** [EpiModel/EpiModel#921]
Howdy @AdrienLeGuillou and @smjenness,

The plotting function is not plotting the quantiles in the correct location.
See attached images below, under incorrect.

A simple edit of line 28 in the plot.R file fixes the problem.
https://github.com/EpiModel/EpiModel/blob/main/R/plot.R#L28
example: polygon(xx+1, yy, col = qnts.pal[j], border = NA)
See attached images below, under correct.

I believe what may be the source of the bug is in line 15.
https://github.com/EpiModel/EpiModel/blob/main/R/plot.R#L15
The "complete.cases" function does not count the NA that is originally present in "qnt.prev" at index 1.
Thus line 15 shifts all the elements forward one indices.
Which results in a plotting at the wrong time points.

I don't know if this causes problems else where, or if the solution above can suffice.

## Incorrect
![example1_incorrect](https://github.com/user-attachments/assets/b3580fa3-04fe-4b68-b919-2d3c895749cc)
![example2_incorrect](https://github.com/user-attachments/assets/512f217f-632f-4636-bf47-77cf79208503)

## correct
![example1](https://github.com/user-attachments/assets/9950b116-73fb-48a7-a7b9-c3fe1b611809)
![example2](https://github.com/user-attachments/assets/9896c1fe-0851-4aa5-865a-befff33d9517)

**Comment by AdrienLeGuillou** [comment]
Thanks for the catch.

I agree that the issue is with the complete case that shifts the values. However your solution only covers the case where a single `NA` is present at the beginning and you would actually create the symmetric issue when the first value is not `NA`. 

Take a look at my PR #922 that fixes it and also covers the case where many `NA`s are present (tracker that start at the same time as an intervention).

The general idea of my fix is to give to `xx` the actual time values and not the indexes of the trimmed `qnt.prev` object.
